/*global before*/
// tests for scrap
// Generated by serverless-mocha-plugin
const mod = require('../src/index.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'Scrap' });

describe('Scrap', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({
        testing: true
    }).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
